### ISSUE TITLE
Pillow doesn't require arabic_reshaper and bidi.algorithm when writing RTL text.

### ISSUE THREAD

**Issue by arastu** [prp-e/zarnevis#1]
Nice work, but I think we don't need arabic_reshaper and bidi.algorithm to write RTL text with Pillow. Since version 8.2.0, Pillow wheels with modified version of [libraqm](https://github.com/HOST-Oman/libraqm) load libfribidi at runtime, if it is installed. By passing the direction argument to .text, pillow is able to support bidirectional text (using FriBiDi), shaping (using HarfBuzz), and properly itemize scripts.

All you need is **libraqm** installed on your machine. (`brew install libraqm`)

Below is an example:
https://gist.github.com/arastu/1ca517ded27deee894feb76d6e96a240

**Comment by prp-e** [comment]
Thanks, didn't know that. 
Although for this particular project, I prefer going with `arabic_reshaper` as I personally want it to be as platform-independent as possible, I mind using `libraqm` or even making this project compatible with that method. 
And again, thanks for your kind feedback on the project 😁

**Comment by arastu** [comment]
It makes sense to be platform-independent 😁.

**Comment by khaledhosny** [comment]
Raqm is as platform independent as Pillow itself.
