### ISSUE TITLE
عدم سازگاری با همه فونت ها

### ISSUE THREAD

**Issue by Clancyov** [prp-e/zarnevis#2]
خیلی عالی 
فقط یک مساله وجود داره اون هم اینه که با همه فونت ها سازگاری نداره. فونت وزیر خوب بود و باهاش کار کرد اما با خیلی از فونتا مثل ب کودک و ... درست کار نمیکنه. و یسری از حروف رو جا میذاره.

**Comment by prp-e** [comment]
فونت‌های سری B استاندارد وب را ندارند.
